variables:
  DOCKER_REGESTRY: 'your-docker-registry'
  PROD_CONTAINER_NAME: "alpine-apk-proxy"
  PROD_IMAGE: ${DOCKER_REGESTRY}/gitlab-ci/${PROD_CONTAINER_NAME}:prod-1.0.1

stages:
  - build
  - deploy

build:
  stage: build
  tags:
     - alpine-apk-proxy-build
  script:
    - echo $REGISTRY_PASSWORD | docker login $DOCKER_REGESTRY -u $REGISTRY_LOGIN --password-stdin
    - docker build --no-cache ./app -t $PROD_IMAGE
    - docker push $PROD_IMAGE
  only:
    - main

deploy:
  stage: deploy
  tags:
    - alpine-apk-proxy-deploy
  script:
    - docker pull $PROD_IMAGE
    - docker stop $PROD_CONTAINER_NAME|| true
    - docker rm $PROD_CONTAINER_NAME || true
    - docker run --name $PROD_CONTAINER_NAME -p 8080:8080 --network=dashboard-net --env-file ./app/config/.env.prod --restart=always -d $PROD_IMAGE
  only:
    - main

